inherits:
    - strictness_veryhigh

ignore-patterns:
  - (^|/)\..+
  - ^docs/
  # ignore tests and bin/ for the moment, their quality does not so much matter.
  - ^bin/
  - ^blessings/tests/
  - ^tools/
  # not maintained
  - ^fabfile.py

test-warnings: true

output-format: grouped

dodgy:
    # Looks at Python code to search for things which look "dodgy"
    # such as passwords or git conflict artifacts
    run: true

frosted:
    # static analysis
    run: true

mccabe:
    # complexity checking.
    run: true

pep257:
    # docstring checking
    run: true

pep8:
    # style checking
    run: true

pyflakes:
    # preferring 'frosted' instead (a fork of)
    run: false

pylint:
    # static analysis and then some
    run: true
    options:
        # pytest module has dynamically assigned functions,
        # raising errors such as: E1101: Module 'pytest' has
        # no 'mark' member
        ignored-classes: pytest
    disable:
        # Access to a protected member _sugar of a client class
        - protected-access

pyroma:
    # checks setup.py
    run: true

vulture:
    # this tool does a good job of finding unused code, which isn't terribly
    # useful from an API perspective, disable.
    run: false

# vim: noai:ts=4:sw=4
